### ISSUE TITLE
Failed to fetch plugin cordova-plugin-usb-serial via registry

### ISSUE THREAD

**Issue by cseoanedeb** [okhiroyuki/cordova-plugin-usb-serial#6]
Hello. I'm trying to use this plugin, but i get stuck at building even without adding any code more than the `cordova add`. I got it work when using the last versión of node and cordova, but all my other plugins start showing errors. There is a minimum versión that I need to reach? I know is a specific scenario, but that will help me a lot. At least identify to wich versións I need to update. Thanks in advance.

Now this is what happens when I try to build with grunt in the project where I already use other cordova plugins. 

ERROR:

```
Fetching plugin "@red-mobile/cordova-plugin-usb-serial" via npm
Fetching plugin "cordova-plugin-usb-serial" via npm
>> Error: Failed to fetch plugin cordova-plugin-usb-serial via registry.
>> Probably this is either a connection problem, or plugin spec is incorrect.
>> Check your connection and plugin name/version/URL.
>> Error: Not found : cordova-plugin-usb-serial
>> 
>> Exited with code: 1.
Warning: Task "exec:android" failed. Use --force to continue.

Aborted due to warnings.
```

VERSIONS:

node/v6.9.1/lib
├── cordova@6.5.0
├── cordova-hot-code-push-cli@1.1.1
├── grunt@1.0.4
├── grunt-cli@1.2.0
├── http-server@14.1.0
├── level@1.4.0
├── npm@3.10.8
└── nw-gyp@3.6.5

NEW CODE:

The only change I made was to add the plugin to cordova. I use one of these at a time in the gruntfile.js but all ends with the same error:
```
                'cordova plugin add cordova-plugin-usb-serial',
                'cordova plugin add @red-mobile/cordova-plugin-usb-serial',
                'cordova plugin add https://github.com/okhiroyuki/cordova-plugin-usb-serial',
```

**Comment by okhiroyuki** [comment]
@cseoanedeb Please use cordova@10 over.
